#!/usr/bin/env python3
"""
MSBuild 辅助脚本：从 version.json + git 生成 VersionInfo.g.cs。

由 SeatFlow.Presentation.Avalonia.csproj 的 GenerateVersionInfo target 在编译前调用。
不写回 version.json，避免每次 build 污染 git working tree。

用法:
  python3 scripts/update_version_info.py --root <项目根> --version-json <path> --output <VersionInfo.g.cs路径>
"""

import argparse
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path


def resolve_root(root_arg: str | None) -> Path:
    """解析项目根目录。"""
    if root_arg:
        return Path(root_arg)
    return Path(__file__).resolve().parent.parent


def get_git_commit(root: Path) -> str:
    """获取当前 HEAD 的 short commit hash。"""
    try:
        result = subprocess.run(
            ["git", "rev-parse", "--short", "HEAD"],
            capture_output=True,
            text=True,
            cwd=str(root),
            check=True,
        )
        return result.stdout.strip()
    except (subprocess.CalledProcessError, FileNotFoundError):
        return "unknown-commit-id"


def get_build_date() -> str:
    """获取带时区的 ISO-8601 构建时间。"""
    return datetime.now(timezone.utc).astimezone().isoformat()


def generate_version_info(
    root: Path, version_json_path: Path, output_path: Path
) -> None:
    """
    读取 version.json，结合 git commit hash 和构建时间，
    生成包含 VersionInfo 静态类的 C# 源文件。
    """
    # 1. 读取 version.json
    with open(version_json_path, encoding="utf-8") as f:
        data = json.load(f)

    version = data.get("version", "0.0.0")

    # 2. 获取 commit hash（从 git 实时获取，不读 version.json）
    commit_id = get_git_commit(root)

    # 3. 构建时间
    build_date = get_build_date()

    # 4. 生成 VersionInfo.g.cs
    content = f"""// Auto-generated by update_version_info.py — do not edit
namespace SeatFlow.Presentation.Avalonia;

internal static class VersionInfo
{{
    public const string Version = "{version}";
    public const string ReleaseTag = "v" + Version;
    public const string CommitId = "{commit_id}";
    public const string BuildDate = "{build_date}";
}}
"""

    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(content, encoding="utf-8", newline="\n")

    print(f"  VersionInfo: {version} (commit: {commit_id}, built: {build_date})")


def main() -> int:
    parser = argparse.ArgumentParser(
        description="从 version.json + git 生成 VersionInfo.g.cs"
    )
    parser.add_argument("--root", default=None, help="项目根目录")
    parser.add_argument("--version-json", required=True, help="version.json 路径")
    parser.add_argument("--output", required=True, help="VersionInfo.g.cs 输出路径")
    args = parser.parse_args()

    root = resolve_root(args.root)
    version_json_path = Path(args.version_json)
    output_path = Path(args.output)

    if not version_json_path.exists():
        print(f"Error: version.json not found: {version_json_path}", file=sys.stderr)
        return 1

    try:
        generate_version_info(root, version_json_path, output_path)
    except Exception as e:
        print(f"Error generating VersionInfo.g.cs: {e}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    sys.exit(main())
