global using SeatFlow.Application.Commands;
global using SeatFlow.Application.Interfaces;
global using SeatFlow.Application.Services;
global using SeatFlow.Core.Models;
global using SeatFlow.Core.Strategies;
global using SeatFlow.Core.Workspace;
global using FluentAssertions;
global using NSubstitute;
global using Xunit;
